name: Lint python
on: [push]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python virtual environment and install tools
        run: |
          python3.12 -m venv venv
          ./venv/bin/python -m ensurepip --upgrade
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/pip install flake8==7.2.0 black==25.1.0 isort==6.0.1

      - name: Check import sorting with isort
        run: ./venv/bin/isort --check-only --diff .

      - name: Lint with flake8
        run: |
          ./venv/bin/flake8 .

      - name: Check formatting with black
        run: |
          ./venv/bin/black --check --verbose .
