name: Typecheck python
on: [push]

jobs:
  typecheck:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python virtual environment and install tools
        run: |
          python3.12 -m venv venv
          ./venv/bin/python -m ensurepip --upgrade
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/python -m pip install -r requirements.txt
          ./venv/bin/pip install mypy==1.16.1

      - name: Typecheck python
        run: ./venv/bin/mypy --install-types --non-interactive .
